fix #278 Handle the send message event on Enter key press
antoine92190/vue-advanced-chat pull request #309
Opened 2022-05-10 13:42 UTC by itTkm

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature #278 
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2022-05-10 13:55 UTC, antoine92190 requested changes

2022-05-10 13:55 UTC, antoine92190 commented on src/lib/Room/RoomFooter/RoomFooter.vue
> +				console.log('keyup', e.isComposing)
Could you remove the `console.log`?

2022-05-10 14:39 UTC, antoine92190 approved these changes

2022-05-10 14:40 UTC, antoine92190 commented
I'd like to have @thu-san feedback before merging this. @thu-san could you test this PR and let us know if it's working on your side as well?

2022-05-14 02:08 UTC, itTkm commented
Hi @thu-san @antoine92190 
Thank you for your feedback @thu-san .
I'm also reproduce that issue in my environment.

I have fixed with 0dc88f5.
Could you please confirm this changes?

https://user-images.githubusercontent.com/61522301/168406838-84d7e90d-e20d-4de9-9f06-5a77d0186292.mov

2022-05-24 07:29 UTC, antoine92190 commented
@thu-san Could you please test this on your side when you have some time?

2022-05-29 05:24 UTC, thu-san commented
@itTkm @antoine92190 
sorry for late reply.
I have checked and it's working fine now!

2022-06-03 06:27 UTC, merged

2022-07-17 15:07 UTC, natsumework commented
@antoine92190  Version 1.5.6 doesn't seem to contain this fix? Could you please release this fix?

2022-07-17 16:37 UTC, antoine92190 commented
Are you using next branch?

2022-07-18 04:34 UTC, natsumework commented
No, I am using master branch. And my package.json is like this.

```
"dependencies": {
    "vue-advanced-chat": "1.5.6"
}
```

I checked the node_modules/vue-advanced-chat folder and made sure it was upgraded to version 1.5.6.

![image](https://user-images.githubusercontent.com/23622184/179445589-11a644e4-7fd8-492f-ad3e-7fbdef0562b6.png)

Also, I confirmed the source code, but it doesn't seem to contain this fix.

![image](https://user-images.githubusercontent.com/23622184/179445721-46a47acf-6f3f-4872-b7e1-95db4c394359.png)

2022-07-19 04:50 UTC, antoine92190 commented
Could you try the new version `1.5.7`?

2022-07-23 10:06 UTC, natsumework commented
@antoine92190 

I'm trying to figure out why some situations are still triggering the "send-message" event accidentally.
According to this reference:  https://github.com/w3c/uievents/issues/202#issuecomment-411238163

The event order will be `composition-start` / `input` / `compotision-end` / `keyup` on Mac.

This order may result in the following situation:

```
isComposed = true
{event: “compositionstart”,  data: “”, isComposing: true}
{event: “input”, data: “z”, isComposing: tru}
{event: “compositionend”, “data: “z”, isComposing: false}
{event: “keyup”, “key”: “z”}
isComposed = true
{event: “keyup”, “key”: “Enter”} // Will send message here
isComposed = true
```

So  it is still possible to accidentally trigger the "send-message" event.

---

It seems to have a different order on windows, so I'm still researching how to solve this problem.